branches:
  only:
    - master
sudo: false
language: python
addons:
  apt:
    packages:
    - enchant
python:
- '2.7'
install:
- pip install -q -r requirements.txt
script:
  - make test
  - make deploy
before_install:
- echo -e "Host docs.plone.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_129e1d4a0f4f_key -iv $encrypted_129e1d4a0f4f_iv
  -in deploy_key.enc -out $HOME/.ssh/id_rsa -d
after_success:
- "./deploy.sh"
